#!/bin/bash

sudo apt update
sudo apt upgrade

sudo apt install -y zsh git xclip

# config git global settings.
git config --global user.name "jiang zhu"
git config --global user.email "m.zhujiang@gmail.com"
git config --global color.ui true

ID_RSA_FILE=~/.ssh/id_rsa.pub
if [ -f "${ID_RSA_FILE}" ]
then
	echo "${ID_RSA_FILE} found."
else
	echo "generate ssh key to access github with git ssh protocol"
	cd ~/
	ssh-keygen -t rsa -b 4096 -C "m.zhujiang@gmail.com"
	eval "$(ssh-agent -s)"
	ssh-add ~/.ssh/id_rsa
	xclip -sel clip < ~/.ssh/id_rsa.pub

	echo "add public ssh_key to github munually please ..."
	# and add ssh_key to github
	# ref: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux
	# for mac user: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-mac

	echo "ref: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux"
	echo "for mac user: https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-mac"

	read -p "Press [Enter] key to continue after adding ssh key to github, ..."
fi

REPO_DIR=~/repo/my_env
if [ -d ${REPO_DIR} ]
then
	echo "${REPO_DIR} existed"
	cd ${REPO_DIR}
	git pull
else
	mkdir -p ~/repo
	cd ~/repo
	# git clone https://github.com/izhujiang/my_env.git
	git clone git@github.com:izhujiang/my_env.git
	cd my_env
fi

export MY_ENV_ROOT=$(cd "$(dirname '$0')";  pwd)
echo "MY_ENV_ROOT location is:${MY_ENV_ROOT}"

source ${MY_ENV_ROOT}/platforms/linux/software_installer_ubuntu

echo "clean up useless packages..."
sudo apt autoremove
