#!/bin/bash

REPO_DIR=~/repo/my_env
if [ -d ${REPO_DIR} ]
then
	echo "${REPO_DIR} existed"
	cd ${REPO_DIR}
	git pull
else
	mkdir -p ~/repo
	cd ~/repo
	# git clone https://github.com/izhujiang/my_env.git
	git clone git@github.com:izhujiang/my_env.git
	cd my_env
fi

export MY_ENV_ROOT=$(cd "$(dirname '$0')";  pwd)
echo "MY_ENV_ROOT location is:${MY_ENV_ROOT}"

source ${MY_ENV_ROOT}/platforms/linux/software_installer_ubuntu
