#!/bin/sh

SYSOS=`uname -s`

# install specific platform tools and packages according to platform
if [ ${SYSOS} = "Linux" ] ; then
  sudo apt install -y zsh
elif [ ${SYSOS} = "Darwin" ] ; then
  sudo brew install zsh
else
  echo "other OS: ${SYSOS}"
fi

sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

