#!/bin/sh


# and setting up envirement variables
for SHELL_CFG in ${HOME}/.zshrc ${HOME}/.bash_profile
do
  echo "export WORKON_HOME=$HOME/.local/virtualenvs" >> $SHELL_CFG
  echo "export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3" >> $SHELL_CFG
  echo "source /usr/local/bin/virtualenvwrapper.sh" >> $SHELL_CFG
done
