#!/bin/sh

# todo; consider when vertualenv is already installed 
# install 3rd party python packages
pip install flake8
pip install future
pip install jedi
pip install mock
pip install nose
pip install PyHamcrest
pip install vertualenv
pip install virtualenvwrapper

# and setting up envirement variables
for SHELL_CFG in ${HOME}/.zshrc ${HOME}/.bash_profile
do
  echo "export WORKON_HOME=$HOME/.local/virtualenvs" >> $SHELL_CFG
  echo "export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3" >> $SHELL_CFG
  echo "source /usr/local/bin/virtualenvwrapper.sh" >> $SHELL_CFG
done
